# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.1.0

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  build: # this can be any name you choose
    working_directory: ~/repo/sub_folder
    executor: node/default # use the default executor defined within the orb
    docker:
    - image: circleci/node:7.10
      environment:
      - CHROME_BIN: /usr/bin/google-chrome
    steps:
    - browser-tools/install-browser-tools
    - checkout:
        path: ~/repo
    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - run: npm install

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    # run tests!
    - run: npm test